### ISSUE TITLE
Is it possible to build a visual studio project for windows 10 64 bit from your repository?

### ISSUE THREAD

**Issue by ahasan016** [tidewise/drivers-camera_onvif#3]
I want to integrate your project into another project of mine and I am struggling to build the library from onvif. Can you help me to make your library usable for windows 10 visual studio project?

**Comment by doudou** [comment]
Oh man.

Not really, no. I have zero development experience on Windows. Moreover, we depend on the gsoap projet for the onvif stuff. Not sure whether this library can be used on Windows / Visual Studio.

Maybe try WSL ?

**Comment by henriquejsfj** [comment]
I don't have experience with Windows either. But maybe these [top 10 projects](https://www.onvif.org/blog/2018/07/12/onvif-challenge-announces-top-10/) would help you if you already didn't pass through it.

**Comment by doudou** [comment]
Closing this. Feel free to reopen if you'd like more information @ahasan016
